# Generated by Django 5.0.2 on 2024-02-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="post_code",
        ),
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
