# Generated by Django 4.1.3 on 2022-11-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
