#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python << END
import sys
import time
import psycopg2

suggest_unrecoverable_after = 30
start = time.time()

while True:
  try:
    psycopg2.connect(
      dbname="${POSTGRES_DB}",
      user="${POSTGRES_USER}",
      password="${POSTGRES_PASSWORD}",
      host="${POSTGRES_HOST}",
      port="${POSTGRES_PORT}",
    )
    break
  except psycopg2.OperationalError as error:
    sys.stderr.write("Waiting for PostgreSQL to become available...\n")
    
    if time.time() - start > suggest_unrecoverable_after:
      sys.stderr.write(f"Taking longer than expected, suggesting unrecoverable error. {error}\n")

  time.sleep(1)
END


python ./manage.py makemigrations
python ./manage.py migrate
python ./manage.py collectstatic --no-input
python ./manage.py runserver